dependencies:

  - name: utils
    version: 1.0.0
    src: htmlwidgets/lib/utils-1.0.0
    script:
      - utils.js
    stylesheet:
      - style.css

  - name: importSettings
    version: 1.0.0
    src: htmlwidgets/lib/importSettings-1.0.0
    script:
      - utils.js
    stylesheet:
      - style.css

  - name: importSettings-style
    version: 1.0.0
    src: htmlwidgets
    stylesheet:
      - importSettings.css

  - name: Sortable
    version: 1.13.0
    src: htmlwidgets/lib/Sortable-1.13.0
    script:
      - Sortable.min.js