version: "3.9"
services:

  shinyproxy:
    build:
      context: .
      target: shinyproxy
    environment:
      - WORK_DIRECTORY=${PWD}
      - PROJECT_DIRECTORY=${PROJECT_DIRECTORY}
      - R_CONFIG_ACTIVE=${R_CONFIG_ACTIVE}
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy-logs/server:/log
      - ./shinyproxy-logs/container:/container-logs
      - ./inst/shinyproxy/application.yml:/opt/shinyproxy/application.yml
      - ./inst/shinyproxy/shinyproxy-2.5.0.jar:/opt/shinyproxy/shinyproxy.jar
      - ./inst/app/www/favicon.ico:/opt/shinyproxy/favicon.ico
    ports:
      - "8080:8080"

networks:
  net:
    name: net
