version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: shiny
    image: naturecons/wheretowork
    ports:
      - "3838:3838"
    environment:
      # environmental variables defined in ./.env that get sent to container
      - FORCE_DEFAULT_PROJECTS
      - PROJECT_DIRECTORY
      - R_CONFIG_ACTIVE
      - GRB_LICENSE_FILE
    volumes:
      - "${PROJECT_DIRECTORY}:/projects"
      - "${PATH_TO_GUROBI_LICENSE}:/opt/gurobi/gurobi.lic:ro"
      