version: "3.9"
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
      target: main
    ports:
      - "3838:3838"
  heroku:
    build:
      context: .
      dockerfile: Dockerfile
      target: heroku
    ports:
      - "3837:3837"
    environment:
      - PORT=3837
