version: "3.9"
services:

  updater:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --schedule "0 0 * * *" --cleanup

  shinyproxy:
    image: openanalytics/shinyproxy:2.5.0
    restart: on-failure
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy-logs/server:/log
      - ./shinyproxy-logs/container:/container-logs
      - ./inst/application.yml:/opt/shinyproxy/application.yml
    ports:
      - "8080:8080"

  # shiny:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: main
  #   image: naturecons/wheretowork:latest
  #   volumes:
  #     - "${PROJECT_DIRECTORY}:/projects"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: "${MEMORY_LIMIT}"
  #   networks:
  #     - net

networks:
  net:
    name: net
