version: "3.9"
services:
  shinyapps:
    build:
      context: .
      dockerfile: Dockerfile
      target: shinyapps
  main:
    build:
      context: .
      dockerfile: Dockerfile
      target: main
    ports:
      - "3838:3838"
