default:
  # golem variables
  golem_name: wheretowork
  golem_version: 0.0.0.9000
  app_prod: no

  # app variables
  ## optimality gap for optimization
  gap: 0.01

  ## mode for importing projects
  ## available options include: "advanced", "beginner", and "project"
  mode: "project"

  ## directory containing the projects
  ## "default" = system.file("extdata", "projects", package = "wheretowork")
  projects: "default"

  ## future plan strategy
  ### if "auto", then:
  ###   if on Shiny apps (per R_CONFIG_ACTIVE variable): "multicore"
  ###   else if on Unix systems: "multicore"
  ###   else "multisession"
  strategy: "auto"

  ## verbosity
  verbose: false

  ## monitor memory usage
  monitor: false

  ## time limit (seconds) for generating solutions
  ## i.e. maximum time that users should wait for when generating solutions
  solver_time_limit: 3600 # one hour

  ## time out (seconds) for worker processes
  ## i.e. maximum time that worker process should remain active after
  ## contacting controller process
  worker_time_out: 3600 # one hour

production:
  mode: "project"
  projects: "/projects"
  strategy: "auto"
  verbose: false
  monitor: false

dev:
  golem_wd: !expr here::here()
