---
title: "Optimization"
output:
  html_document:
    toc: true
    fig_caption: true
    toc_float: true
    number_sections: true
bibliography: references.bib
csl: methods-in-ecology-and-evolution.csl
---

# Introduction

This article is intended for users already familiar with the basic functionality
of the Where to Work tool. It is recommended to first read the [official manual](https://ncc-cnc.github.io/wheretowork/articles/articles/wtw_manual.html)
before proceeding.

The goal of this article is to provide an understanding of the optimization procedures that the Where to Work tool uses to generate prioritizations. Specifically, the Where to Work tool uses exact algorithm solvers (i.e., [Gurobi](https://www.gurobi.com/) and [CBC](https://github.com/coin-or/Cbc)) to generate prioritizations. Briefly, this article will (i) provide an overview of exact algorithms, (ii) discuss the advantages and disadvantageous of exact algorithms, (iii) describe the general rationale behind how exact algorithms work, and (iv) provide an illustrative example of applying a type of example algorithm (i.e., branch and bound) to a sample optimization problem. Although it is beyond the scope of this article to provide a detail understanding of the inner workings of all types of exact algorithms, this article intends to provide enough information so that users of the Where to Work tool can feel comfortable applying these algorithms.

# Overview of exact algorithms

Exact algorithms are a class of algorithms that guarantee optimality [reviewed in @rTODO]. There are many different algorithms that are classified as exact algorithms, including the branch and bound method [@rTODO], branch and cut method, simplex algorithm [@rTODO], and barrier algorithm [@rTODO]. Broadly speaking, exact algorithms can solve various types of optimization problems. For example, the simplex algorithm can solve linear optimization problems that contain only continuous decision variables (termed "linear programming problems"). Additionally, the branch and bound method can solve linear optimization problems that contain only integer decision variables (termed "integer programming problems") and those that contain both integer and continuous decision variables (termed "mixed integer programming problems").  These algorithms have been applied to many different tasks, such as facility location [@rTODO], job scheduling [@rTODO], and route optimization [@rTODO]. They are also becoming increasingly popular for conservation decision making [@rTODO].

The Where to Work tool uses exact algorithms to generate prioritizations. To achieve this, it interfaces with external optimization software that solves optimization problems using exact algorithms (termed "exact algorithm solvers"). Currently, the Where to Work tool can support either [Gurobi](https://www.gurobi.com/) or [CBC](https://github.com/coin-or/Cbc). Exact algorithm solvers often support multiple different algorithms so they can solve a wide variety of optimization problems. For example, the Gurobi software supports many different algorithms, including the interior point algorithm, barrier algorithm, branch and bound search processes, and various simplex algorithms. Additionally, exact algorithm solvers may use heuristic algorithms -- a class of iterative algorithms that do not guarantee optimality -- to aid with optimization [@rTODO]. They may also apply presolve algorithms -- a class of algorithms designed to simplify and reduce the size of optimization problems -- prior to optimization [@rTODO]. Although it is beyond the scope of this article to describe exactly which algorithms a particular exact algorithm solver will apply to a given optimization problem, this will hopefully provide an overview of the algorithms that they employ.

# Advantages and disadvantages of exact algorithm solvers

There are numerous advantages with using exact algorithm solvers. A key advantage is that exact algorithms provide guarantees on solution quality. For example, if required, they can solve problems to optimality. In other words, they can identify the best possible solution to a mathematical optimization problem. Also, if strict optimality is not required, they can solve problems to within a pre-specified optimality gap (e.g., identify a solution that is within 10% of optimality). As such, by using exact algorithms to generate prioritizations, conservation practitioners can be confident in the quality of a prioritizations. Although other types of algorithms can be applied to conservation problems [e.g., heuristic or meta-heuristic algorithms; @rTODO], they do not provide such guarantees and, as such, may require re-running the optimization process tens of thousands of times to verify solution quality [@rTODO]. Additionally, exact algorithm solvers can be readily applied to a wide variety of problems. Because the Where to Work tool uses exact algorithm solvers, it can potentially be applied many to different types of conservation planning problems. For instance, the Where to Work tool can be used to generate (i) prioritizations that minimize cost whilst ensuring all goals are met (i.e., a "minimum set reserve selection problem") and (ii) prioritizations that aim to reach as many goals as possible, whilst ensuring that the total selected area does not exceed a pre-specified budget (i.e., a "budget-limited reserve selection problem"). Furthermore, another advantage of using exact algorithm solvers is that they are steadily increasing in performance over time [@rTODO]. By interfacing with exact algorithm solvers, this means that the Where to Work tool can provide access to these improvements as newer versions of the solvers become available over time.

There are several disadvantages with using exact algorithm solvers. A key disadvantage is that the best performing exact algorithm solvers are commercial software (e.g., [Gurobi](https://www.gurobi.com/) and [IBM CPLEX](https://www.ibm.com/products/ilog-cplex-optimization-studio)). Although open source exact algorithm solvers are available (e.g., [CBC](https://github.com/coin-or/Cbc), [HiGHS](https://highs.dev/), and [SYMPHONY](https://github.com/coin-or/SYMPHONY)), they generally cannot solve optimization problems as quickly as the commercial solvers and nor can they generally solve as large-scale problems as commercial solvers [@rTODO]. Commercial solvers often provide special free licenses for academic use (e.g., [Gurobi](https://www.gurobi.com/academia/academic-program-and-licenses/) and [IBM CPLEX](https://www.ibm.com/support/pages/ibm-ilog-optimization-academic-initiative)); however, commercial licenses may be required for use by governmental, commercial, and non-governmental organizations. As such, organizations may need to carefully consider the potential benefits and costs associated with using commercial solvers. Another disadvantage is that exact algorithms can be much slower than other types of algorithms. For example, heuristic algorithms -- while they cannot guarantee solution quality -- can generate near-optimal solutions to optimization problems faster than exact algorithms [@rTODO]. Indeed, the Zonation decision support tool -- which is powered by iterative heuristic algorithms -- can likely solve budget-limited reserve selection problems faster than the Where to Work tool [@rTODO]. Finally, it can be challenging to solve large-scale non-linear problems with exact algorithms. Although this limits that types of problems that exact algorithm solvers can be applied to in practical settings, many conservation planning problems can be expressed as linear programming, integer programming, and mixed integer programming problems [@rTODO].

# Explanation of how exact algorithms work

TODO.

# Illustrative example of exact algorithms

TODO.

# References
