name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      HEROKU_APP_NAME: wheretowork
      DOCKERHUB_IMAGE: naturecons/wheretowork
      DOCKERHUB_TAG: devel
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_EMAIL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        run:
          heroku container:login
      - name: Build and push
        run:
          docker pull ${DOCKERHUB_IMAGE}:${DOCKERHUB_TAG}
          heroku container:push --app ${HEROKU_APP_NAME} web
      - name: Release
        run:
          heroku container:release --app ${HEROKU_APP_NAME} web

# see here for more information:
# https://hosting.analythium.io/deploying-shiny-apps-to-heroku-with-docker-and-github-actions/
